version: '3'
services:
  web:
    build: .
    ports:
      - "5173:5173" # React
      - "9005:9005"
    volumes:
      - .:/app  
      - /app/node_modules 
    environment:
      - CHOKIDAR_USEPOLLING=true 
    stdin_open: true
    tty: true
    command: ["npm", "run", "dev"]

  story-book:
    build: .
    ports:
      - "6006:6006" # Storybook 
    volumes:
      - .:/app  
      - /app/node_modules 
    environment:
      - CHOKIDAR_USEPOLLING=true 
    stdin_open: true
    tty: true
    command: ["npm", "run", "storybook"]